export const PROFILE_COPY = {
  'pt-BR': {
    welcome: 'Bem-vindo ao GUIA DOA',
    languageTitle: 'Escolha seu idioma',
    languageSubtitle: 'Você poderá alterar essa opção depois nas configurações.',
    profileEyebrow: 'CONFIGURAÇÃO DO PERFIL',
    profileTitle: 'Seu perfil de comandante',
    profileSubtitle: 'Personalize o guia com seu nome e o reino em que você joga.',
    unofficialTitle: 'Aplicativo comunitário não oficial',
    unofficialText: 'O GUIA DOA é uma ferramenta independente criada para auxiliar jogadores e não possui vínculo oficial com a Deca Games.',
    identity: 'Informações do jogador',
    name: 'Nome do comandante',
    namePlaceholder: 'Como você é conhecido no jogo',
    playerId: 'ID do jogador',
    playerIdHint: 'Opcional',
    playerIdPlaceholder: 'Ex.: 12345678',
    realmSection: 'Seu reino',
    realm: 'Reino',
    realmClock: 'Horário do reino',
    privacy: 'Estas informações ficam apenas no seu dispositivo e podem ser alteradas depois.',
    continue: 'Entrar no GUIA DOA',
    save: 'Salvar alterações',
    back: 'Voltar',
    validation: 'Informe seu nome e selecione um reino para continuar.',
    selectRealm: 'Selecionar reino',
    filter: 'Filtrar',
    allRegions: 'Todas as regiões',
    loadingRealms: 'Carregando reinos…',
    noRealms: 'Nenhum reino disponível nesta região',
    realmCount: (shown, total) => `${shown} de ${total} reinos`,
  },
  'en-US': {
    welcome: 'Welcome to GUIA DOA',
    languageTitle: 'Choose your language',
    languageSubtitle: 'You can change this option later in settings.',
    profileEyebrow: 'PROFILE SETUP',
    profileTitle: 'Your commander profile',
    profileSubtitle: 'Personalize the guide with your name and the realm where you play.',
    unofficialTitle: 'Unofficial community app',
    unofficialText: 'GUIA DOA is an independent player utility and is not officially affiliated with Deca Games.',
    identity: 'Player information',
    name: 'Commander name',
    namePlaceholder: 'How you are known in the game',
    playerId: 'Player ID',
    playerIdHint: 'Optional',
    playerIdPlaceholder: 'e.g. 12345678',
    realmSection: 'Your realm',
    realm: 'Realm',
    realmClock: 'Realm time',
    privacy: 'This information stays on your device and can be changed later.',
    continue: 'Open GUIA DOA',
    save: 'Save changes',
    back: 'Back',
    validation: 'Enter your name and select a realm to continue.',
    selectRealm: 'Select realm',
    filter: 'Filter',
    allRegions: 'All regions',
    loadingRealms: 'Loading realms…',
    noRealms: 'No realms available in this region',
    realmCount: (shown, total) => `${shown} of ${total} realms`,
  },
};

export function getProfileCopy(locale) {
  return PROFILE_COPY[locale] || PROFILE_COPY['pt-BR'];
}
