const img = slug => `/assets/items/catalog/${slug}.webp`;
const price = (valor, valorOriginal = null) => ({ moeda:'rubis', valor, valorOriginal });
const effect = (tipo, valor = null, unidade = '') => ({ tipo, valor, unidade });
const content = (itemSlug, quantidade = 1) => ({ itemSlug, quantidade });

/**
 * Catálogo recuperado dos screenshots fornecidos na Beta 2.58.
 * Só há preço quando o valor estava legível no botão verde do jogo.
 * A migração de conteúdo usa merge preservador: campos já editados no MongoDB não são sobrescritos.
 */
export const ITEM_SCREENSHOT_CATALOG = [
  // ── Acelerações ──────────────────────────────────────────────────────────
  { slug:'gotas-marcha-forcada', nome:'Gotas de Marcha Forçada', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('gotas-marcha-forcada'), preco:price(7), efeito:effect('reducao_marcha',25,'percentual'), ordem:100,
    descricao:'Reduz o tempo de uma marcha em 25%.', uso:'Use para reduzir o tempo de uma marcha em andamento.' },
  { slug:'aceleracao-1-minuto', nome:'Aceleração de 1 Minuto', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-1-minuto'), preco:price(1), efeito:effect('aceleracao',1,'minutos'), ordem:110,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 1 minuto.' },
  { slug:'aceleracao-5-minutos', nome:'Aceleração de 5 Minutos', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-5-minutos'), preco:price(3), efeito:effect('aceleracao',5,'minutos'), ordem:120,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 5 minutos.' },
  { slug:'aceleracao-15-minutos', nome:'Aceleração de 15 Minutos', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-15-minutos'), preco:price(5), efeito:effect('aceleracao',15,'minutos'), ordem:130,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 15 minutos.' },
  { slug:'aceleracao-1-hora', nome:'Aceleração de 1 Hora', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-1-hora'), preco:price(10), efeito:effect('aceleracao',1,'horas'), ordem:140,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 1 hora.' },
  { slug:'aceleracao-2-5-horas', nome:'Aceleração de 2,5 Horas', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-2-5-horas'), preco:price(15), efeito:effect('aceleracao',2.5,'horas'), ordem:150,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 2,5 horas.' },
  { slug:'aceleracao-8-horas', nome:'Aceleração de 8 Horas', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-8-horas'), preco:price(40), efeito:effect('aceleracao',8,'horas'), ordem:160,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 8 horas.' },
  { slug:'aceleracao-15-horas', nome:'Aceleração de 15 Horas', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-15-horas'), preco:price(65), efeito:effect('aceleracao',15,'horas'), ordem:170,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 15 horas.' },
  { slug:'aceleracao-24-horas', nome:'Aceleração de 24 Horas', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-24-horas'), preco:price(95), efeito:effect('aceleracao',24,'horas'), ordem:180,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 24 horas.' },
  { slug:'aceleracao-2-5-dias', nome:'Aceleração de 2,5 Dias', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-2-5-dias'), preco:price(210), efeito:effect('aceleracao',2.5,'dias'), ordem:190,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 2,5 dias.' },
  { slug:'aceleracao-4-dias', nome:'Aceleração de 4 Dias', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('aceleracao-4-dias'), preco:price(275), efeito:effect('aceleracao',4,'dias'), ordem:200,
    descricao:'Acelere um Treino, Construção ou Pesquisa em 4 dias.' },
  { slug:'gotas-recuperacao-forcada', nome:'Gotas de Recuperação Forçada', grupo:'aceleracoes', categoria:'Acelerações', imagem:img('gotas-recuperacao-forcada'), efeito:effect('reducao_recuperacao',25,'percentual'), ordem:210,
    descricao:'Reduz o tempo de recuperação em 25%.' },

  // ── Recursos ─────────────────────────────────────────────────────────────
  { slug:'80-000-metais', nome:'80.000 Metais', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-metais'), quantidade:80000, preco:price(16), efeito:effect('recurso',80000,'metais'), ordem:300, descricao:'Adiciona 80.000 Metais à sua cidade.' },
  { slug:'250-000-metais', nome:'250.000 Metais', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-metais'), quantidade:250000, preco:price(44), efeito:effect('recurso',250000,'metais'), ordem:310, descricao:'Adiciona 250.000 Metais à sua cidade.' },
  { slug:'80-000-pedra', nome:'80.000 de Pedra', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-pedra'), quantidade:80000, preco:price(16), efeito:effect('recurso',80000,'pedra'), ordem:320, descricao:'Adiciona 80.000 de Pedra à sua cidade.' },
  { slug:'250-000-pedra', nome:'250.000 de Pedra', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-pedra'), quantidade:250000, preco:price(44), efeito:effect('recurso',250000,'pedra'), ordem:330, descricao:'Adiciona 250.000 de Pedra à sua cidade.' },
  { slug:'80-000-ouro', nome:'80.000 de Ouro', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-ouro'), quantidade:80000, preco:price(16), efeito:effect('recurso',80000,'ouro'), ordem:340, descricao:'Adiciona 80.000 de Ouro à sua cidade.' },
  { slug:'250-000-ouro', nome:'250.000 de Ouro', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-ouro'), quantidade:250000, preco:price(44), efeito:effect('recurso',250000,'ouro'), ordem:350, descricao:'Adiciona 250.000 de Ouro à sua cidade.' },
  { slug:'80-000-comida', nome:'80.000 de Comida', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-comida'), quantidade:80000, preco:price(16), efeito:effect('recurso',80000,'comida'), ordem:360, descricao:'Adiciona 80.000 de Comida à sua cidade.' },
  { slug:'250-000-comida', nome:'250.000 de Comida', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-comida'), quantidade:250000, preco:price(44), efeito:effect('recurso',250000,'comida'), ordem:370, descricao:'Adiciona 250.000 de Comida à sua cidade.' },
  { slug:'80-000-madeira', nome:'80.000 de Madeira', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-madeira'), quantidade:80000, preco:price(16), efeito:effect('recurso',80000,'madeira'), ordem:380, descricao:'Adiciona 80.000 de Madeira à sua cidade.' },
  { slug:'250-000-madeira', nome:'250.000 de Madeira', grupo:'recursos', categoria:'Recursos', imagem:img('recurso-madeira'), quantidade:250000, preco:price(44), efeito:effect('recurso',250000,'madeira'), ordem:390, descricao:'Adiciona 250.000 de Madeira à sua cidade.' },

  // ── Geral ─────────────────────────────────────────────────────────────────
  { slug:'obsidiana', nome:'Obsidiana', grupo:'geral', categoria:'Materiais', imagem:img('obsidiana'), preco:price(1), ordem:500, descricao:'Usada para aprimorar edificações acima do Nv. 20. Obtida através de torneios e atividades.' },
  { slug:'essencia-da-furia', nome:'Essência da Fúria', grupo:'geral', categoria:'Dragão', imagem:img('essencia-furia'), preco:price(5), ordem:510, descricao:'Aprimore Habilidades do Dragão.' },
  { slug:'10x-essence-of-fury', nome:'10X Essence of Fury', grupo:'geral', categoria:'Dragão', imagem:img('essencia-furia'), quantidade:10, preco:price(45), ordem:520, descricao:'Pacote com 10 unidades de Essence of Fury.' },
  { slug:'50x-essence-of-fury', nome:'50X Essence of Fury', grupo:'geral', categoria:'Dragão', imagem:img('essencia-furia'), quantidade:50, preco:price(200), ordem:530, descricao:'Pacote com 50 unidades de Essence of Fury.' },
  { slug:'teleportador-sombrio', nome:'Teleportador Sombrio', grupo:'geral', categoria:'Teleporte', preco:price(30), ordem:540, descricao:'Teleporte sua Cidade para um local aleatório.' },
  { slug:'teleportador-direcionado', nome:'Teleportador Direcionado', grupo:'geral', categoria:'Teleporte', preco:price(75), ordem:550, descricao:'Teleporte sua cidade para um local disponível para construir uma cidade.' },
  { slug:'tubo-multiplicador-elixir-antropo', nome:'Tubo Multiplicador de Elixir Antropo', grupo:'geral', categoria:'Antropo', preco:price(10), ordem:560, descricao:'x2 preenchimento de Orbe.' },
  { slug:'multiplicador-leve-elixir-antropo', nome:'Multiplicador Leve de Elixir Antropo', grupo:'geral', categoria:'Antropo', preco:price(20), ordem:570, descricao:'x4 preenchimento de Orbe.' },
  { slug:'tratado-cessar-fogo', nome:'Tratado de Cessar-fogo', grupo:'geral', categoria:'Proteção', preco:price(25), ordem:580, descricao:'Você não pode atacar/ser atacado por 12hr. Use quando não estiver lutando ou marchando.' },
  { slug:'alterador-identidade', nome:'Alterador de Identidade', grupo:'geral', categoria:'Conta', preco:price(10), ordem:590, descricao:'Muda o nome de seu Jogador, Cidade ou Dragão.' },
  { slug:'coracoes-de-dragao', nome:'Corações de Dragão', grupo:'geral', categoria:'Bônus', preco:price(10), ordem:600, descricao:'Aumenta o Ataque das tropas em 20% por 24 horas.' },
  { slug:'escudos-brilhantes', nome:'Escudos Brilhantes', grupo:'geral', categoria:'Bônus', preco:price(10), ordem:610, descricao:'Aumenta a Defesa das tropas em 20% por 24 horas.' },
  { slug:'nulificador-de-massa', nome:'Nulificador de Massa', grupo:'geral', categoria:'Construção', preco:price(7), ordem:620, descricao:'Destrói uma Edificação sua.' },
  { slug:'finalizacao', nome:'Finalização', grupo:'geral', categoria:'Construção', preco:price(40), ordem:630, descricao:'Use para aprimorar uma edificação.' },
  { slug:'sangue-de-salamandra', nome:'Sangue de Salamandra', grupo:'geral', categoria:'Dragão', preco:price(39), ordem:640, descricao:'Desbloqueie níveis de dragão de 40 a 49!' },
  { slug:'essencia-de-fosforo', nome:'Essência de Fósforo', grupo:'geral', categoria:'Dragão', preco:price(39), ordem:650, descricao:'Desbloqueie níveis de dragão de 30 a 39!' },
  { slug:'essencia-de-enxofre', nome:'Essência de Enxofre', grupo:'geral', categoria:'Dragão', preco:price(39), ordem:660, descricao:'Desbloqueie níveis de dragão de 21 a 29!' },
  { slug:'escritura-expansao-terra', nome:'Escritura de Expansão da Terra', grupo:'geral', categoria:'Expansão', preco:price(100), ordem:670, descricao:'Usado para desbloquear os 10 trechos restantes da Ilha da Terra.' },
  { slug:'escritura-expansao-fogo', nome:'Escritura de Expansão do Fogo', grupo:'geral', categoria:'Expansão', preco:price(100), ordem:680, descricao:'Usado para desbloquear 10 áreas na Ilha do Fogo.' },
  { slug:'escritura-expansao-beladona', nome:'Escritura de Expansão Beladona', grupo:'geral', categoria:'Expansão', preco:price(100), ordem:690, descricao:'Usada para desbloquear 10 áreas na Ilha Beladona.' },
  { slug:'moeda-dos-desejos', nome:'Moeda dos Desejos', grupo:'geral', categoria:'Moedas', preco:price(20), ordem:700, descricao:'Use no evento Pedra dos Desejos para obter recompensas incríveis.' },
  { slug:'pergaminho-devastar', nome:'Pergaminho Devastar', grupo:'geral', categoria:'Combate', preco:price(60), ordem:710,
    descricao:'Usado na opção Devastar da Campanha para obter recompensas sem realizar cada ataque manualmente.',
    origem:'Obtido a partir dos Zyrvorthians e trocado na Loja de Surpresas.',
    uso:'Na Campanha, escolha Devastar, defina a quantidade e selecione o dragão ligado à armadura desejada.',
    limites:'Até 99 usos por dia. A troca/construção leva cerca de 6 horas; esse tempo ainda está em validação.',
    tags:['campanha','grodz','devastar','zyrvorthian','armadura'],
    i18n:{ 'en-US':{
      nome:'Devastate Scroll', categoria:'Combat',
      descricao:'Used by the Campaign Devastate option to collect rewards without performing each attack manually.',
      origem:'Obtained through Zyrvorthian activity and exchanged in the Surprise Shop.',
      uso:'In Campaign, choose Devastate, set the amount, and select the dragon tied to the armor you want.',
      limites:'Up to 99 uses per day. The exchange/build takes about 6 hours; this time is still being validated.',
    } } },
  { slug:'chamado-de-guerra', nome:'Chamado de Guerra', grupo:'geral', categoria:'Expedição', preco:price(5), ordem:720, descricao:'Ao usá-lo, você ganha uma chance adicional de desafio na Expedição do Dragão Voador.' },
  { slug:'rocha-ilha-flutuante', nome:'Rocha da Ilha Flutuante', grupo:'geral', categoria:'Ilhas Flutuantes', preco:price(2), ordem:730, descricao:'Itens comuns usados para aprimorar as construções nas Ilhas Flutuantes.' },
  { slug:'flecha', nome:'Flecha', grupo:'geral', categoria:'Torre de Vigilância', preco:price(2), ordem:740, descricao:'Usado para aprimorar sua Torre de Vigilância.' },
  { slug:'po-de-testronius', nome:'Pó de Testronius', grupo:'geral', categoria:'Especial', ordem:750, descricao:'Item especial mostrado como conteúdo da Arca do Início.' },
  { slug:'pergaminho-de-cura', nome:'Pergaminho de Cura', grupo:'geral', categoria:'Cura', ordem:760, descricao:'Pergaminho usado para cura.' },

  // Nanos — os preços e durações estavam legíveis na categoria Geral.
  { slug:'nanos-comida-1-dia', nome:'Nanos de Comida: 1 Dia', grupo:'geral', categoria:'Nanos', preco:price(7), efeito:effect('producao',25,'percentual_1_dia'), ordem:800, descricao:'Produção de comida +25% por 24 horas.' },
  { slug:'nanos-comida-1-semana', nome:'Nanos de Comida: 1 Semana', grupo:'geral', categoria:'Nanos', preco:price(40), efeito:effect('producao',25,'percentual_7_dias'), ordem:810, descricao:'Produção de comida +25% por 7 dias.' },
  { slug:'nanos-madeira-1-dia', nome:'Nanos de Madeira: 1 Dia', grupo:'geral', categoria:'Nanos', preco:price(7), efeito:effect('producao',25,'percentual_1_dia'), ordem:820, descricao:'Produção de madeira +25% por 24 horas.' },
  { slug:'nanos-madeira-1-semana', nome:'Nanos de Madeira: 1 Semana', grupo:'geral', categoria:'Nanos', preco:price(40), efeito:effect('producao',25,'percentual_7_dias'), ordem:830, descricao:'Produção de madeira +25% por 7 dias.' },
  { slug:'nanos-pedra-1-dia', nome:'Nanos de Pedra: 1 Dia', grupo:'geral', categoria:'Nanos', preco:price(7), efeito:effect('producao',25,'percentual_1_dia'), ordem:840, descricao:'Produção de pedra +25% por 24 horas.' },
  { slug:'nanos-pedra-1-semana', nome:'Nanos de Pedra: 1 Semana', grupo:'geral', categoria:'Nanos', preco:price(40), efeito:effect('producao',25,'percentual_7_dias'), ordem:850, descricao:'Produção de pedra +25% por 7 dias.' },
  { slug:'nanos-metal-1-dia', nome:'Nanos de Metal: 1 Dia', grupo:'geral', categoria:'Nanos', preco:price(7), efeito:effect('producao',25,'percentual_1_dia'), ordem:860, descricao:'Produção de metais +25% por 24 horas.' },
  { slug:'nanos-metal-1-semana', nome:'Nanos de Metal: 1 Semana', grupo:'geral', categoria:'Nanos', preco:price(40), efeito:effect('producao',25,'percentual_7_dias'), ordem:870, descricao:'Produção de metais +25% por 7 dias.' },

  // ── Arcas / recipientes ───────────────────────────────────────────────────
  { slug:'arca-do-inicio', nome:'Arca do Início', grupo:'arcas', categoria:'Arcas', imagem:img('arca-inicio'), preco:price(250), destaque:true, ordem:900,
    descricao:'Limite 1: Contém recursos, Aceleração e um EXCLUSIVO Pó de Testronius!',
    conteudo:[content('aceleracao-15-minutos',5),content('aceleracao-1-hora',3),content('aceleracao-2-5-horas',2),content('aceleracao-8-horas',2),content('po-de-testronius',1),content('80-000-pedra',1),content('80-000-metais',1),content('80-000-madeira',1)] },
  { slug:'bolsa-de-cronos', nome:'Bolsa de Cronos', grupo:'arcas', categoria:'Arcas', imagem:img('bolsa-cronos'), preco:price(345), destaque:true, ordem:910,
    descricao:'Bolsa com Acelerações e Nulificadores de Massa.',
    conteudo:[content('aceleracao-1-minuto',10),content('aceleracao-5-minutos',9),content('aceleracao-15-minutos',8),content('aceleracao-1-hora',6),content('aceleracao-2-5-horas',4),content('aceleracao-8-horas',3),content('aceleracao-15-horas',2),content('nulificador-de-massa',5)] },
  { slug:'10-000-pergaminhos-de-cura', nome:'10.000 Pergaminhos de Cura', grupo:'arcas', categoria:'Cura', quantidade:10000, preco:price(1), ordem:920,
    descricao:'Você obtém 10.000 pergaminhos de cura.', conteudo:[content('pergaminho-de-cura',10000)] },
  { slug:'caixas-de-nanos', nome:'Caixas de Nanos', grupo:'arcas', categoria:'Nanos', imagem:img('caixas-nanos'), preco:price(145), ordem:930,
    descricao:'Nanos de 1 Semana de cada tipo.', conteudo:[content('nanos-comida-1-semana'),content('nanos-madeira-1-semana'),content('nanos-pedra-1-semana'),content('nanos-metal-1-semana')] },
  { slug:'latas-de-nanos', nome:'Latas de Nanos', grupo:'arcas', categoria:'Nanos', imagem:img('latas-nanos'), preco:price(25), ordem:940,
    descricao:'Nanos de 1 Dia de cada tipo.', conteudo:[content('nanos-comida-1-dia'),content('nanos-madeira-1-dia'),content('nanos-pedra-1-dia'),content('nanos-metal-1-dia')] },
  { slug:'arca-teleporte-posse', nome:'Arca de Teleporte e Posse', grupo:'arcas', categoria:'Arcas', imagem:img('arca-teleporte-posse'), preco:price(80), ordem:950,
    descricao:'2x Tratado de Cessar-fogo, 2x Teleportador Sombrio.', conteudo:[content('tratado-cessar-fogo',2),content('teleportador-sombrio',2)] },
  { slug:'pasta-de-finalizacao', nome:'Pasta de Finalização', grupo:'arcas', categoria:'Arcas', imagem:img('pasta-finalizacao'), preco:price(155), ordem:960,
    descricao:'Contém 5x Finalização.', conteudo:[content('finalizacao',5)] },
  { slug:'13th-anniversary-chest-iv', nome:'13th Anniversary Chest IV', grupo:'arcas', categoria:'Arcas', imagem:img('arca-aniversario-iv'), preco:price(29), ordem:970,
    descricao:'This Mystery Chest contains the items for the events.', conteudoObservacao:'O screenshot mostra conteúdo aleatório com diferentes quantidades; relações exatas não foram fixadas porque as alternativas não estavam totalmente legíveis.' },
  { slug:'13th-anniversary-chest-iv-premium', nome:'13th Anniversary Chest IV (Premium)', grupo:'arcas', categoria:'Arcas', imagem:img('arca-aniversario-iv-premium'), preco:price(49,55), ordem:980,
    descricao:'This Mystery Chest contains the items for the events.', conteudoObservacao:'Versão Premium com conteúdo aleatório. O preço promocional visível é 49 Rubis e o valor anterior mostrado é 55.' },
  { slug:'arca-superior-grande-dragao', nome:'Arca Superior do Grande Dragão', grupo:'arcas', categoria:'Armadura de Dragão', imagem:img('arca-superior-grande-dragao'), preco:price(95), ordem:990,
    descricao:'1 parte aleatória da Armadura do Grande Dragão.', conteudoObservacao:'Concede 1 parte aleatória da Armadura do Grande Dragão.' },
  { slug:'arca-superior-dragao-agua', nome:'Arca Superior do Dragão da Água', grupo:'arcas', categoria:'Armadura de Dragão', imagem:img('arca-superior-dragao-agua'), preco:price(95), ordem:1000,
    descricao:'1 parte aleatória da Armadura do Dragão da Água.', conteudoObservacao:'Concede 1 parte aleatória da Armadura do Dragão da Água.' },
  { slug:'arca-superior-dragao-terra', nome:'Arca Superior do Dragão da Terra', grupo:'arcas', categoria:'Armadura de Dragão', imagem:img('arca-superior-dragao-terra'), preco:price(95), ordem:1010,
    descricao:'1 pedaço aleatório de Armadura de Dragão da Terra.', conteudoObservacao:'Concede 1 pedaço aleatório de Armadura de Dragão da Terra.' },
  { slug:'arca-superior-dragao-fogo', nome:'Arca Superior do Dragão do Fogo', grupo:'arcas', categoria:'Armadura de Dragão', imagem:img('arca-superior-dragao-fogo'), preco:price(95), ordem:1020,
    descricao:'1 parte aleatória da Armadura do Dragão do Fogo.', conteudoObservacao:'Concede 1 parte aleatória da Armadura do Dragão do Fogo.' },
];
