import React, { useMemo, useState } from 'react';
import { C } from '../../theme.js';
import { useI18n } from '../../hooks/useI18n.jsx';
const make=()=>({id:Date.now()+Math.random(),valor:'',qtd:'1'});
export default function TorneioGeneral(){
  const {t,locale}=useI18n(); const [rows,setRows]=useState([make(),make()]);
  const total=useMemo(()=>rows.reduce((s,r)=>s+(parseInt(r.valor)||0)*(parseInt(r.qtd)||0),0),[rows]);
  const upd=(id,k,v)=>setRows(a=>a.map(r=>r.id===id?{...r,[k]:v.replace(/\D/g,'')}:r));
  return <div className="max-w-md mx-auto pb-4" style={{animation:'reveal-up .4s ease both'}}>
    <div className="rounded-xl overflow-hidden mb-3" style={{border:`1.5px solid ${C.BORDER}`}}><div className="px-4 py-3" style={{background:'linear-gradient(135deg,#2A0A0A,#5A1A1A)'}}><p className="font-nunito font-bold text-[0.72rem] uppercase m-0" style={{color:'rgba(220,160,140,.75)'}}>{t('torneio.general.badge')}</p><p className="font-nunito font-black m-0 mt-1" style={{fontSize:'1.15rem',color:'#F0A090'}}>🎖️ {t('torneio.titulo.general')}</p></div><div className="px-4 py-3" style={{background:C.BG_CARD}}><p className="m-0 font-nunito font-semibold text-[0.78rem]" style={{color:C.TEXT_SECONDARY}}>{t('torneio.general.calc_help')}</p></div></div>
    <div className="rounded-xl overflow-hidden" style={{border:`1px solid ${C.BORDER_SOFT}`,background:C.BG_CARD}}><div className="px-4 py-3" style={{background:C.NAVY,color:'#fff'}}><small className="font-nunito font-bold uppercase">{t('torneio.aceleracoes.total_pontos')}</small><strong className="block text-3xl font-black">{total.toLocaleString(locale)}</strong></div><div className="p-3 grid gap-2">{rows.map((r,i)=><div className="tournament-general-row" key={r.id}><div><label>{t('torneio.general.card_value')}</label><input className="tw-input" inputMode="numeric" placeholder="100" value={r.valor} onChange={e=>upd(r.id,'valor',e.target.value)}/></div><div><label>{t('torneio.general.quantity')}</label><input className="tw-input" inputMode="numeric" placeholder="1" value={r.qtd} onChange={e=>upd(r.id,'qtd',e.target.value)}/></div><strong>{((parseInt(r.valor)||0)*(parseInt(r.qtd)||0)).toLocaleString(locale)} pts</strong>{rows.length>1?<button className="btn-ghost btn-sm" onClick={()=>setRows(a=>a.filter(x=>x.id!==r.id))}>×</button>:null}</div>)}<button className="btn-ghost btn-sm" onClick={()=>setRows(a=>[...a,make()])}>＋ {t('torneio.general.add_material')}</button><p className="font-nunito text-[0.72rem] leading-relaxed m-0" style={{color:C.TEXT_MUTED}}>{t('torneio.general.calc_note')}</p></div></div>
  </div>;
}
